### ISSUE TITLE
Question: How can I get the spot prices aws/azure? 

### ISSUE THREAD

**Issue by xlcbingo1999** [stanford-futuredata/gavel#242]
It's necessary to generate the prices file aws/azure for us to run the policy with SLO.
Is it possible to open-source the way how I can find the prices?
Or is it possible to detail the attributes in 'log/aws' and 'log/azure'?

**Comment by deepakn94** [comment]
Not in this repository, but we have a repository for a related project with scripts to do this: https://github.com/stanford-futuredata/training_on_a_dime/tree/master/scripts.
