### ISSUE TITLE
The operation of shutil.rmtree

### ISSUE THREAD

**Issue by JoeyYoung** [stanford-futuredata/gavel#244]
Hi all,

Thanks for your excellent work. Just a small note when playing around with the framework, will you consider modifying the part of creating checkpoint_dir in line 73 of worker.py? I think the action of shutil.rmtree is dangerous and I almost deleted my whole workspace since I set the path outside the gavel directory (that's my fault of course) :(

**Comment by deepakn94** [comment]
Can you create a PR? Happy to fix this behavior!
